### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-appointmentplus-source#3]
Will close with #1 

Endpoints
- GetCustomers
Add an option to have the timestamp be the date of the last run of the workflow.

[TechnicalGuide.pdf](https://github.com/aries-data/aries-activity-appointmentplus-source/files/677654/TechnicalGuide.pdf)
[DataDictionary.pdf](https://github.com/aries-data/aries-activity-appointmentplus-source/files/677655/DataDictionary.pdf)
[Appointment Callouts (1) (1).pdf](https://github.com/aries-data/aries-activity-appointmentplus-source/files/677656/Appointment.Callouts.1.1.pdf)

**Comment by ryw** [comment]
no more work on aries
